#! /bin/sh
### BEGIN INIT INFO
# Provides:          ppckbavrd
# Required-Start:    $syslog
# Required-Stop:     $syslog
# Default-Start:     S
# Default-Stop:      0 6
# Short-Description: AVR monitoring daemon
# Description:       Power/Init button monitoring, etc.
### END INIT INFO

PATH=/sbin:/bin:/usr/sbin:/usr/bin
DAEMON=/usr/sbin/ppckbavrd
NAME=ppckbavrd
DESC="AVR monitoring daemon"
PIDFILE=/var/run/$NAME.pid

test -f $DAEMON || exit 0

set -e

case "$1" in
  start)
	echo -n "Starting $DESC: "
	start-stop-daemon --start --quiet --pidfile $PIDFILE --exec $DAEMON
	echo "$NAME."
	;;
  stop)
	echo -n "Stopping $DESC: "
	start-stop-daemon --oknodo --stop --quiet --pidfile $PIDFILE --name $NAME
	echo "$NAME."
	;;
  restart|force-reload)
	echo -n "Restarting $DESC: "
	start-stop-daemon --stop --quiet --pidfile $PIDFILE --name $NAME
	sleep 1
	start-stop-daemon --start --quiet --pidfile $PIDFILE --exec $DAEMON
	echo "$NAME."
	;;
  *)
	N=/etc/init.d/$NAME
	echo "Usage: $N {start|stop|restart|force-reload}" >&2
	exit 1
	;;
esac

exit 0
